require('plugin_config.color')
require('plugin_config.syntax')
require('plugin_config.extra')
require('plugin_config.navigation')
require('plugin_config.gestures')
require('plugin_config.git')
require('plugin_config.neon')
